
celeri:

  gmailCredentialsPath: x
  gmailTokensPath: x
  sendingEmail: x
  adminsEmail: x
  adminsPhoneNumber: x

  smsBrana:
    login: x
    password: x

  notifications:
    emailNotifications:
      -
        recipientAddress: x
        emailSubject: x
        emailMessageResourcePath: x
        heartbeatToTriggerMinutes: x

    smsNotifications:
      -
        recipientPhoneNumber: x
        smsMessageResourcePath: x
        heartbeatToTriggerMinutes: x

# ------------------
# Spring Actuator
# ------------------

management:
  endpoint.shutdown.enabled: true
  endpoints:
    web.exposure.include: "*"
    shutdown.enabled: true
